const manageMenu = [
    {
        name: '首页',
        path: '/Admin',
        icon: 'icon-shouye',
        dataTitle: '首页',
        dataIntro: '展示统计信息',
    },
    {
        name: '车辆档案',
        path: '/Admin/vehicles',
        icon: 'icon-cheliangxiangqing',
        dataTitle: '车辆档案',
        dataIntro: '港口所有车辆信息展示',
    },
    {
        name: '地图配置',
        path: '/Admin/mapTool',
        icon: 'icon-ditugongju',
        dataTitle: '港口地图',
        dataIntro: '港口内地图的展示',
    },
    {
        name: '设备配置',
        path: '/Admin/moduleConfig',
        icon: 'icon-mokuaipeizhi',
        dataTitle: '模块配置',
        dataIntro: '港口所有设备信息的展示',
    },
    {
        name: '运营记录',
        path: '/Admin/ModuleOperation',
        icon: 'icon-mokuaipeizhi',
        dataTitle: '运营问题记录',
        dataIntro: '运营问题历史记录',
    },
    {
        name: '历史统计',
        path: '/Admin/faults',
        icon: 'icon-guzhangtongji',
        dataTitle: '历史统计',
        dataIntro: '车辆历史故障信息',
    },
    {
        name: '邮件转发',
        path: '/Admin/mail',
        icon: 'icon-youjianzhuanfa',
        dataTitle: '邮件转发',
        dataIntro: '发送邮件信息',
    },
    {
        name: '使用说明',
        path: '/Admin/help',
        icon: 'icon-shiyongshuoming',
        dataTitle: '使用说明',
        dataIntro: '系统使用介绍',
    },
    {
        name: '车辆调度',
        path: '/Admin/CarPools',
        icon: 'icon-shiyongshuoming',
        dataTitle: '车辆调度',
        dataIntro: '车辆调度',
    },
    {
        name: '版本信息',
        path: '/Admin/version',
        // icon: <GithubOutlined />,
        icon: 'icon-banbenxinxi',
        dataTitle: '版本信息',
        dataIntro: '系统历史更新内容',
    },
];
const userMenu = [
    {
        name: '首页',
        path: '/Admin',
        icon: 'icon-yunyingshuju',
        dataTitle: '首页',
        dataIntro: '展示统计信息',
    },
    {
        name: '地图工具',
        path: '/Admin/mapTool',
        icon: 'icon-ditugongju',
        dataTitle: '港口地图',
        dataIntro: '港口内地图的展示',
    },
    {
        name: '历史统计',
        path: '/Admin/faults',
        icon: 'icon-guzhangtongji',
        dataTitle: '历史统计',
        dataIntro: '车辆历史故障信息',
    },
    {
        name: '邮件转发',
        path: '/Admin/mail',
        icon: 'icon-youjianzhuanfa',
        dataTitle: '邮件转发',
        dataIntro: '发送邮件信息',
    },
    {
        name: '使用说明',
        path: '/Admin/help',
        icon: 'icon-shiyongshuoming',
        dataTitle: '使用说明',
        dataIntro: '系统使用介绍',
    },
    {
        name: '版本信息',
        path: '/Admin/version',
        // icon: <GithubOutlined />,
        icon: 'icon-banbenxinxi',
        dataTitle: '版本信息',
        dataIntro: '系统历史更新内容',
    },
];

const menu = [
    {
        name: '首页',
        path: '/Admin',
        icon: 'icon-shouye',
        dataTitle: '首页',
        dataIntro: '展示统计信息',
    },
    {
        name: '车辆管理',
        dataTitle: '车辆管理',
        dataIntro: '港口所有车辆信息展示',
        icon: 'icon-cheliangguanli',
        children: [
            {
                name: '车辆档案',
                path: '/Admin/vehicles',
                icon: 'icon-cheliangxiangqing',
                dataTitle: '车辆档案',
                dataIntro: '港口所有车辆信息展示',
                tab: '车辆管理',
            },
            {
                name: '车辆出勤',
                path: '/Admin/CarPools',
                icon: 'icon-shiyongshuoming',
                dataTitle: '车辆出勤',
                dataIntro: '车辆出勤',
                tab: '车辆管理',
            },
        ],
    },
    {
        name: '效率统计',
        path: '/Admin/faults',
        icon: 'icon-guzhangtongji',
        dataTitle: '效率统计',
        dataIntro: '车辆历史故障信息',
    },
    {
        name: '运营记录',
        path: '/Admin/ModuleOperation',
        icon: 'icon-yunyingjilu',
        dataTitle: '运营纪录',
        dataIntro: '车辆历史故障信息',
    },
    {
        name: '高级',
        dataTitle: '高级',
        dataIntro: '地图配置和邮件转发',
        icon: 'icon-ruanjianshengji',
        children: [
            {
                name: '地图配置',
                path: '/Admin/mapTool',
                icon: 'icon-ditugongju',
                dataTitle: '港口地图',
                dataIntro: '港口内地图的展示',
                tab: '高级',
            },
            {
                name: '邮件转发',
                path: '/Admin/mail',
                icon: 'icon-youjianzhuanfa',
                dataTitle: '邮件转发',
                dataIntro: '发送邮件信息',
                tab: '高级',
            },
        ],
    },
    {
        name: '关于',
        dataTitle: '关于',
        dataIntro: '使用说明和版本信息',
        icon: 'icon-mokuaipeizhi',
        children: [
            {
                name: '使用说明',
                path: '/Admin/help',
                icon: 'icon-shiyongshuoming',
                dataTitle: '使用说明',
                dataIntro: '系统使用介绍',
                tab: '关于',
            },

            {
                name: '版本信息',
                path: '/Admin/version',
                icon: 'icon-banbenxinxi',
                dataTitle: '版本信息',
                dataIntro: '系统历史更新内容',
                tab: '关于',
            },
        ],
    },
];

export default {
    manageMenu,
    userMenu,
    menu,
};
